.TH "Répertoire de référence de C:/Users/mat20/Desktop/GameJam_MiniJam#112/UnityProject_EvilWare/Assets/Scripts/Widgets" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de C:/Users/mat20/Desktop/GameJam_MiniJam#112/UnityProject_EvilWare/Assets/Scripts/Widgets
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBClock\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBHightScoreObject\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBLeaderboard\&.cs\fP"
.br
.in -1c
