.TH "GameManager.Player" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameManager.Player
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBPlayer\fP (string name)"
.br
.ti -1c
.RI "\fBPlayer\fP (string name, string id)"
.br
.ti -1c
.RI "void \fBSetName\fP (string valueString)"
.br
.ti -1c
.RI "void \fBSetID\fP (string valueString)"
.br
.ti -1c
.RI "void \fBSetConnected\fP (bool valueBool)"
.br
.ti -1c
.RI "void \fBSetScore\fP (int valueInt)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBID\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsConnected\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBScore\fP\fC [get]\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB66\fP du fichier \fBGameManager\&.cs\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "GameManager\&.Player\&.Player (string name)"

.PP
Définition à la ligne \fB83\fP du fichier \fBGameManager\&.cs\fP\&.
.SS "GameManager\&.Player\&.Player (string name, string id)"

.PP
Définition à la ligne \fB91\fP du fichier \fBGameManager\&.cs\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void GameManager\&.Player\&.SetConnected (bool valueBool)"

.PP
Définition à la ligne \fB109\fP du fichier \fBGameManager\&.cs\fP\&.
.SS "void GameManager\&.Player\&.SetID (string valueString)"

.PP
Définition à la ligne \fB104\fP du fichier \fBGameManager\&.cs\fP\&.
.SS "void GameManager\&.Player\&.SetName (string valueString)"

.PP
Définition à la ligne \fB99\fP du fichier \fBGameManager\&.cs\fP\&.
.SS "void GameManager\&.Player\&.SetScore (int valueInt)"

.PP
Définition à la ligne \fB114\fP du fichier \fBGameManager\&.cs\fP\&.
.SH "Documentation des propriétés"
.PP 
.SS "string GameManager\&.Player\&.ID\fC [get]\fP"

.PP
Définition à la ligne \fB79\fP du fichier \fBGameManager\&.cs\fP\&.
.SS "bool GameManager\&.Player\&.IsConnected\fC [get]\fP"

.PP
Définition à la ligne \fB80\fP du fichier \fBGameManager\&.cs\fP\&.
.SS "string GameManager\&.Player\&.Name\fC [get]\fP"

.PP
Définition à la ligne \fB78\fP du fichier \fBGameManager\&.cs\fP\&.
.SS "int GameManager\&.Player\&.Score\fC [get]\fP"

.PP
Définition à la ligne \fB81\fP du fichier \fBGameManager\&.cs\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EvilWare à partir du code source\&.
