.TH "GameManager.HightScore" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameManager.HightScore
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBHightScore\fP (int place=\-1, string name='Billy', int \fBscore\fP=0)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBrank\fP"
.br
.ti -1c
.RI "string \fBnamePlayer\fP"
.br
.ti -1c
.RI "int \fBscore\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB123\fP du fichier \fBGameManager\&.cs\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "GameManager\&.HightScore\&.HightScore (int place = \fC\-1\fP, string name = \fC'Billy'\fP, int score = \fC0\fP)"

.PP
Définition à la ligne \fB131\fP du fichier \fBGameManager\&.cs\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "string GameManager\&.HightScore\&.namePlayer"

.PP
Définition à la ligne \fB128\fP du fichier \fBGameManager\&.cs\fP\&.
.SS "int GameManager\&.HightScore\&.rank"

.PP
Définition à la ligne \fB127\fP du fichier \fBGameManager\&.cs\fP\&.
.SS "int GameManager\&.HightScore\&.score"

.PP
Définition à la ligne \fB129\fP du fichier \fBGameManager\&.cs\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EvilWare à partir du code source\&.
