.TH "HightScoreObject" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HightScoreObject
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de MonoBehaviour\&.
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "Image \fBimageRank\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBrank\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBname\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBscore\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB7\fP du fichier \fBHightScoreObject\&.cs\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "Image HightScoreObject\&.imageRank"

.PP
Définition à la ligne \fB9\fP du fichier \fBHightScoreObject\&.cs\fP\&.
.SS "TextMeshProUGUI HightScoreObject\&.name"

.PP
Définition à la ligne \fB11\fP du fichier \fBHightScoreObject\&.cs\fP\&.
.SS "TextMeshProUGUI HightScoreObject\&.rank"

.PP
Définition à la ligne \fB10\fP du fichier \fBHightScoreObject\&.cs\fP\&.
.SS "TextMeshProUGUI HightScoreObject\&.score"

.PP
Définition à la ligne \fB12\fP du fichier \fBHightScoreObject\&.cs\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EvilWare à partir du code source\&.
