.TH "InputThree.IDefaultActions" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputThree.IDefaultActions
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBOnInputLeft\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnInputRight\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnInputEnter\fP (InputAction\&.CallbackContext context)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB227\fP du fichier \fBInputThree\&.cs\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void InputThree\&.IDefaultActions\&.OnInputEnter (InputAction\&.CallbackContext context)"

.SS "void InputThree\&.IDefaultActions\&.OnInputLeft (InputAction\&.CallbackContext context)"

.SS "void InputThree\&.IDefaultActions\&.OnInputRight (InputAction\&.CallbackContext context)"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EvilWare à partir du code source\&.
