.TH "Leaderboard" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leaderboard
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de MonoBehaviour\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBUpList\fP (float valueFloat)"
.br
.ti -1c
.RI "void \fBDownList\fP (float valueFloat)"
.br
.ti -1c
.RI "void \fBUpdateList\fP (List< \fBGameManager\&.HightScore\fP > listHightScores)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "int \fBCountList\fP\fC [get]\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB6\fP du fichier \fBLeaderboard\&.cs\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void Leaderboard\&.DownList (float valueFloat)"

.PP
Définition à la ligne \fB52\fP du fichier \fBLeaderboard\&.cs\fP\&.
.SS "void Leaderboard\&.UpdateList (List< \fBGameManager\&.HightScore\fP > listHightScores)"

.PP
Définition à la ligne \fB62\fP du fichier \fBLeaderboard\&.cs\fP\&.
.SS "void Leaderboard\&.UpList (float valueFloat)"

.PP
Définition à la ligne \fB43\fP du fichier \fBLeaderboard\&.cs\fP\&.
.SH "Documentation des propriétés"
.PP 
.SS "int Leaderboard\&.CountList\fC [get]\fP"

.PP
Définition à la ligne \fB41\fP du fichier \fBLeaderboard\&.cs\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EvilWare à partir du code source\&.
