.TH "LevelGladiaJump" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelGladiaJump
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBLevelManager\fP\&.
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB5\fP du fichier \fBLevelGladiaJump\&.cs\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EvilWare à partir du code source\&.
