.TH "LevelManager" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelManager
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de MonoBehaviour\&.
.PP
Dérivée par \fBLevelGladiaJump\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBFinishIntro\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "virtual void \fBStartLevel\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdateLevel\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBInputThree\fP \fB_inputs\fP"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "static \fBLevelManager\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB6\fP du fichier \fBLevelManager\&.cs\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void LevelManager\&.FinishIntro ()"

.PP
Définition à la ligne \fB72\fP du fichier \fBLevelManager\&.cs\fP\&.
.SS "virtual void LevelManager\&.StartLevel ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne \fB61\fP du fichier \fBLevelManager\&.cs\fP\&.
.SS "virtual void LevelManager\&.UpdateLevel ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne \fB67\fP du fichier \fBLevelManager\&.cs\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBInputThree\fP LevelManager\&._inputs\fC [protected]\fP"

.PP
Définition à la ligne \fB43\fP du fichier \fBLevelManager\&.cs\fP\&.
.SH "Documentation des propriétés"
.PP 
.SS "\fBLevelManager\fP LevelManager\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Définition à la ligne \fB16\fP du fichier \fBLevelManager\&.cs\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EvilWare à partir du code source\&.
