.TH "MenuManager" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MenuManager
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de MonoBehaviour\&.
.SH "Description détaillée"
.PP 
Définition à la ligne \fB7\fP du fichier \fBMenuManager\&.cs\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EvilWare à partir du code source\&.
