.TH "PlayfabManager" 3 "Jeudi 24 Novembre 2022" "Version 0.1.0" "EvilWare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayfabManager
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de MonoBehaviour\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBLogin\fP ()"
.br
.ti -1c
.RI "void \fBSendLeaderboard\fP ()"
.br
.ti -1c
.RI "void \fBGetLeaderboard\fP ()"
.br
.ti -1c
.RI "void \fBUpdateDisplayName\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB8\fP du fichier \fBPlayfabManager\&.cs\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void PlayfabManager\&.GetLeaderboard ()"

.PP
Définition à la ligne \fB105\fP du fichier \fBPlayfabManager\&.cs\fP\&.
.SS "void PlayfabManager\&.Login ()"

.PP
Définition à la ligne \fB53\fP du fichier \fBPlayfabManager\&.cs\fP\&.
.SS "void PlayfabManager\&.SendLeaderboard ()"

.PP
Définition à la ligne \fB82\fP du fichier \fBPlayfabManager\&.cs\fP\&.
.SS "void PlayfabManager\&.UpdateDisplayName ()"

.PP
Définition à la ligne \fB132\fP du fichier \fBPlayfabManager\&.cs\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour EvilWare à partir du code source\&.
